markdown: rdiscount
pygments: true
permalink: 
rdiscount:
  extensions: [smart]
exclude: [ Gemfile, Gemfile.lock, gems, _assets, bower_components ]
title : Sam WOlfand
production_url : www.github.com/swolfand/swolfand.github.io
description: "Thoughts, flamewars, utilities, tutorials, codes, projects and other things by
analytics:
gauges: 50f2b533613f5d7c8000000c
author :
  name : Sam Wolfand
  github : swolfand
  twitter : swolfand
  email: samwolfand@gmail.com
baseurl: ""
