markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
title : Matt Beedle
production_url : http://mattbeedle.name
description: "Blog attempt 5, by Matt Beedle"
disqus_shortname: mattbeedleblog
analytics: UA-43466624-1
gauges: 50f2b533613f5d7c8000000c
author :
  name : Matt Beedle
  github : mattbeedle
  twitter : mattbeedle
  email: mattbeedle@gmail.com
